### ISSUE TITLE
About java 11 requirement

### ISSUE THREAD

**Issue by sbernard31** [eclipse/dash-licenses#108]
Currently `dash-licenses` **is requiring java 11**.

I guess one day the idea is to be able to add the Maven Dash-licenses plugin to maven build and failed if dependencies are not checked. 
In this case, this will make for all project build to require java 11. Some could not want this and so this could limit the adoption.  

Knowing that, 
Java8 will live for some years (2026/2030), maybe even more then java11(2024/2026)   : 
 - [Adopt OpenJDK Release Roadmap](https://adoptopenjdk.net/support.html#roadmap)
 - [Oracle Java SE Product Releases](https://www.oracle.com/java/technologies/java-se-support-roadmap.html)

Maybe for this kind of tooling, it would be better to target java8 than java 11 ? 
Unless there is strong constraint which make this impossible ?

**Comment by mickaelistria** [comment]
Do you have concrete need for Java 8 support in a project?

**Comment by sbernard31** [comment]
Currently : 
-  our project ([Leshan](https://github.com/eclipse/leshan/)) target java8 and so must be built with a JDK 8 for release.
-  the maven build required java8 at minimal version to be run. 

If we integrated `dash-licenses` we should : 
 - pass at java11 at minimal version to run maven build (at least for launching this goal)
 - and probably use toolchain to still be able to build with JDK 8.

It's doable but if there is no blocking issue to use java8 as minimal version for `dash-licenses`, I guess this could maybe make the life easier for some projects ?

**Comment by waynebeaton** [comment]
We use some APIs that were introduced after Java 8. Reverting would be hard.  WONTFIX

**Comment by sbernard31** [comment]
Many maven-plugin are moving to java11 as minimal version.

And I discover recently the `--release` option of JVM (available since java9) (better late than never ...)
This allow to create artifact compatible with older JVM (much more easily than using toolchain)

So no more a problem for us. (see :https://github.com/eclipse-leshan/leshan/issues/1412)

Thanks for looking into this, and sorry I didn't let you know that sooner.
