### ISSUE TITLE
Question about `license-check` goal behavior ?

### ISSUE THREAD

**Issue by sbernard31** [eclipse/dash-licenses#109]
I begin to experiment to integrate  `license-tool-plugin` to my maven build.
(Tested to check [leshan](https://github.com/eclipse/leshan) project with dash-licenses commit b60d3f272653ffd0161e7de93ac1f6b30fc70563)

I do something like this :
```xml
<plugins>
    <plugin>
        <groupId>org.eclipse.dash</groupId>
        <artifactId>license-tool-plugin</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <executions>
            <execution>
                <id>license-check</id>
                <phase>verify</phase>
                <goals>
                    <goal>license-check</goal>
                </goals>
            </execution>
        </executions>
    </plugin>
</plugins>
```

I have a multi-module project.
I see that a `dash/summary` file is created in each module.
But all the file contains exactly the same summary. 
It seems this is a flat version of all the dependencies of the project.

I expected : 
- 1 summary in the root module containing all dependencies in it.
- or (probably more in maven spirit) 1 summary in each module containing only the dependencies related to the module.

Or maybe I don't get something ? 

If you want to "make fail the build when review is needed" with : 
```xml
<plugins>
  <plugin>
        <groupId>org.eclipse.dash</groupId>
        <artifactId>license-tool-plugin</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <executions>
            <execution>
                <id>license-check</id>
                <phase>verify</phase>
                <goals>
                    <goal>license-check</goal>
                </goals>
                <configuration>
                    <failWhenReviewNeeded>false</failWhenReviewNeeded>
                </configuration>
            </execution>
        </executions>
    </plugin>
</plugins>
```

You will face the same kind of "strange" behavior, I mean the build will fail on the first module even if this module does not depends to any problematic library. (I guess for same reason)

**Comment by sbernard31** [comment]
If I understand you well, the goal should be executed once even in multi-module project.

Reading the [`LicenseCheckMojo`](https://github.com/eclipse/dash-licenses/blob/e1f6ab87b9239b8a5af08a852065aef9de8c0117/maven-plugin/src/main/java/org/eclipse/dash/licenses/maven/LicenseCheckMojo.java#L52) and [Mojo Documentation](https://maven.apache.org/developers/mojo-api-specification.html#the-descriptor-and-annotations), I undestand that `aggregator=true` and `inheritByDefault = false` should do it. :thinking: 

I tried to force the `<inherited>false</inherited>` in my build like this : 
```xml
<plugin>
    <groupId>org.eclipse.dash</groupId>
    <artifactId>license-tool-plugin</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <inherited>false</inherited>
    <executions>
        <execution>
            <id>license-check</id>
            <goals>
                <goal>license-check</goal>
            </goals>
            <configuration>
                <failWhenReviewNeeded>false</failWhenReviewNeeded>
            </configuration>
        </execution>
    </executions>
</plugin>
```
and it works as expected. 

So it's like  there is a bug or a misunderstanding about `inheritByDefault = false`.
I found this bug [MPLUGIN-375](https://issues.apache.org/jira/browse/MPLUGIN-375), I'm not sure this is linked I will try to get some information about that. 

I'm using  : 
> Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.12, vendor: Debian, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: fr_FR, platform encoding: UTF-8
OS name: "linux", version: "5.10.0-8-amd64", arch: "amd64", family: "unix"

**Comment by mbooth101** [comment]
@sbernard31 That hack is a bit horrible, I submitted a PR with the proper way to do it. See PR #133

**Comment by sbernard31** [comment]
@mbooth101  I tested it locally with my project and now it works as expected without needing to add `<inherited>false</inherited>` :+1:
