### ISSUE TITLE
More sophisticated parsing/matching of SPDX expressions

### ISSUE THREAD

**Issue by waynebeaton** [eclipse/dash-licenses#12]
The is a quick and dirty "for now" solution. The reasoning is that a conjunctive expression is weird and needs attention. For expressions that include disjunction, we just split on the disjunction and see if the required license is in the list. For single license expressions, we just string match the text. This is good enough for many (perhaps most or almost all) cases.

The ``LicenseSupport#getStatus`` method is used to determine whether or not we can accept content distributed under terms described by a particular SPDX expression.

e.g. 

```java
licenseSupport.getStatus("EPL-2.0") => Status.Approved
licenseSupport.getStatus("GPL-2.0") => Status.Restricted
licenseSupport.getStatus("EPL-2.0 OR GPL-2.0") => Status.Approved
licenseSupport.getStatus("EPL-2.0 AND GPL-2.0") => Status.Restricted
```

Where it gets tricky (and this is likely a corner case) is when conjunction and disjunction are both present. The following expressions should be approved because EPL-2.0 is fine. But the current implementation will reject them because of the "AND" (again, the current implementation is "quick and dirty").

```java
licenseSupport.getStatus("EPL-2.0 OR (GPL-2.0 AND Apache-2.0)") => Status.Rejected
licenseSupport.getStatus("EPL-2.0 OR (MIT AND Apache-2.0)") => Status.Rejected
```

I don't think that this actually impacts us, but the SPDX representation of licenses with exceptions has changed. I don't think that this impacts any licenses that are currently on our white list. e.g., ``GPL-2.0 WITH Classpath-exception-2.0`` (deprecated) is equivalent to ``GPL-2.0-with-classpath-exception``. Again, since any use of GPL-2.0 requires investigation by the IP Team, this particular case probably isn't an issue for us.

In any case (and as much as I love to build parsers), I have to believe that there is an existing library that can help us with this.

**Comment by sschuberth** [comment]
You may want to look at ORT's [spdx-utils library](https://github.com/oss-review-toolkit/ort/tree/master/spdx-utils) for parsing SPDX expressions and eventually take it into use. Currently, we only have artifacts on [JitPack](https://github.com/oss-review-toolkit/ort#from-binaries), but we plan to [have releases on Maven Central](https://github.com/oss-review-toolkit/ort/issues/2906) soon.

**Comment by waynebeaton** [comment]
I had an immediate need so I wrote a simple parser and evaluator by hand.

https://github.com/eclipse/dash-licenses/blob/master/src/test/java/org/eclipse/dash/licenses/tests/SpdxExpressionParserTests.java

At some point, we should re-evaluate and explore replacing this implementation with a third-party library. I'm closing this issue for now.
