### ISSUE TITLE
wrong results for jgit 6.1.0

### ISSUE THREAD

**Issue by msohn** [eclipse/dash-licenses#150]
I ran the dash IP log tool on jgit's stable-6.1 branch.

It wrongly reports the following sshd dependency information:
```
maven/mavencentral/org.apache.sshd/sshd-common/2.8.0, Apache-2.0, restricted, clearlydefined
maven/mavencentral/org.apache.sshd/sshd-core/2.8.0, Apache-2.0, restricted, clearlydefined
maven/mavencentral/org.apache.sshd/sshd-osgi/2.8.0, Apache-2.0, restricted, clearlydefined
maven/mavencentral/org.apache.sshd/sshd-sftp/2.8.0, Apache-2.0, restricted, clearlydefined
```

jgit 6.1.0 does not use sshd-common and sshd-core but only sshd-osgi and sshd-sftp which were approved in CQ23892 and  CQ23893

I manually corrected this to
```
maven/mavencentral/org.apache.sshd/sshd-osgi/2.8.0, Apache-2.0, approved, CQ23892
maven/mavencentral/org.apache.sshd/sshd-sftp/2.8.0, Apache-2.0, approved, CQ23893
```
in https://git.eclipse.org/r/c/jgit/jgit/+/191424

**Comment by waynebeaton** [comment]
> Why doesn't the tool find the CQs which approved sshd-sftp and sshd-osgi ?

Not sure. I'll investigate.

**Comment by msohn** [comment]
Excluding sshd-core and sshd-common in maven dependencies prevents that the ip log tool lists them as jgit dependencies.
See https://git.eclipse.org/r/c/jgit/jgit/+/191429

**Comment by waynebeaton** [comment]
The problem was that the license on the CQ was left as "Pending". With no license information, the CQ was excluded from the search. A lot of CQs have been left with "Pending" as their license, which isn't right. I'll take that up with the IT team.

In the meantime, I've provided the license information on those two CQs and the two libraries appear to be passing now.

**Comment by waynebeaton** [comment]
BTW, I added a feature that helps the Dash License Tool deal with _works with_ dependencies. If you pass a `-Ddash.projectId=technology.jgit`, it will flag the `jmh-core` and `jmh-generator-annprocess` as approved.

````
$ mvn org.eclipse.dash:license-tool-plugin:license-check -Ddash.summary=DEPENDENCIES -Ddash.projectId=technology.jgit
````

DEPENDENCIES:
````
...
maven/mavencentral/org.openjdk.jmh/jmh-core/1.32, GPL-2.0-only with Classpath-exception-2.0, approved, #959
maven/mavencentral/org.openjdk.jmh/jmh-generator-annprocess/1.32, GPL-2.0-only with Classpath-exception-2.0, approved, #962
...
````

**Comment by msohn** [comment]
thanks, now the output seems correct for the JGit project

Is there a way to configure these options in our pom.xml as configuration of the license-tool-plugin ?
This would help to simplify running the tool.

**Comment by msohn** [comment]
https://git.eclipse.org/r/c/jgit/jgit/+/191433
is the result of generating DEPENDENCIES with option `-Ddash.projectId=technology.jgit`

-> sshd and jmh artefacts are now classified correctly
