### ISSUE TITLE
Github workflow - option to define location of pom.xml

### ISSUE THREAD

**Issue by stbischof** [eclipse/dash-licenses#190]
one of the Requirements of GitHub workflow is the location of the `pom.xml`
```
    Root pom.xml must reside in the repository root
```

please add an option to override this with an custom location.

**Comment by waynebeaton** [comment]
Maven has an option for this.

`mvn -f path/to/pom.xml ...`

The Maven support uses the standard Maven reactor. Specifying the location of a pom.xml file in a mojo does not, AFAIK, make sense.
