### ISSUE TITLE
Too eagerly assume all npm modules come from npm.js

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/dash-licenses#192]
In Wild Web Developer package-lock.json, we have
```json
    "node_modules/vscode-css-languageserver": {
      "version": "1.0.0",
      "resolved": "file:target/vscode-css-languageserver-1.0.0.tgz",
      "integrity": "sha512-+jenuZRhU9Ym0cHzU08X47w/nPcnid2qTZVaHmD55Nu5771rRIRTg7NaQvgCn+sh82iJfJLKzKbJHvPH/Lyp2Q==",
      "license": "MIT",
      "dependencies": {
        "vscode-css-languageservice": "^6.1.1",
        "vscode-languageserver": "^8.1.0-next.1",
        "vscode-uri": "^3.0.6"
      },
      "engines": {
        "node": "*"
      }
    },
```
and some others like
```json
    "node_modules/vscode-css-languageserver/node_modules/vscode-uri": {
      "version": "3.0.6",
      "resolved": "https://registry.npmjs.org/vscode-uri/-/vscode-uri-3.0.6.tgz",
      "integrity": "sha512-fmL7V1eiDBFRRnu+gfRWTzyPpNIHJTc4mWnFkwBUmO9U3KPgJAmTx7oxi2bl/Rh6HLdU7+4C9wlj0k2E4AdKFQ=="
    },
```

Compare the `resolved` property: the former tells that this is a local NPM module, not something from npm.js (in practice it's a module extracted from VSCode archive).  But dash-license tools still generates some coordinates of the form `npm/npmjs/-/vscode-css-languageserver/1.0.0` for it, which is incorrect.
In such case, I imagine something like `npm/file:target\/vscode-css-languageserver-1.0.0.tgz/-/vscode-css-languageserver/1.0.0` would be more correct.

**Comment by waynebeaton** [comment]
I wouldn't describe it as "eager". It's just wrong.

A better answer, like what you're suggesting, will make the tool more usable. 

`npm/file:target\/vscode-css-languageserver-1.0.0.tgz/-/vscode-css-languageserver/1.0.0`

The second bit (what ClearlyDefined calls the "source") just repeats information that's included in other parts of the ID. Perhaps we can just go with "local" or similar...

It's unlikely that we'll be able to automatically find the source code which will mean that the committer will have to attach that. But once we find and scan it, Dash would stop bugging you about it...

I think that it's a relatively easy fix. Can you give me a direct pointer to a `package-lock.json` file that we can use to test?
