### ISSUE TITLE
Dash License Tool Maven plugin marks an Orbit provided/approved dependency as failing

### ISSUE THREAD

**Issue by vrubezhny** [eclipse/dash-licenses#195]
When building a PR for WildWebDeveloper project an Orbit-provided dependency is marked as failing by Dash License Tool Maven Plugin:

```
[INFO] --- license-tool-plugin:0.0.1-SNAPSHOT:license-check (default-cli) @ parent ---
[INFO] Querying Eclipse Foundation for license data for 498 items.
[INFO] Found 482 items.
[INFO] Querying ClearlyDefined for license data for 14 items.
[INFO] Found 14 items.
[INFO] License information could not be automatically verified for the following content:
[INFO] 
[INFO] p2/orbit/p2.eclipse.plugin/org.apache.commons.compress/1.21.0.v20211103-2100
[INFO] 
[INFO] This content is either not correctly mapped by the system, or requires review.
[INFO] Summary file was written to: /home/runner/work/wildwebdeveloper/wildwebdeveloper/target/dash/summary
Error:  Dependency license check failed. Some dependencies need to be vetted.
```

**Comment by vrubezhny** [comment]
@waynebeaton It's an artifact that appears when copy-pasting from the GitHub action build log  -  it's like a job number and a link to the job that failed.
This "siffix" is not used/presented in the dependency list generated and passed to the Dash License Tool  for analysis.
 You can see this log at:  https://github.com/eclipse/wildwebdeveloper/actions/runs/3658040632/jobs/6182327676#step:9:212

**Comment by vrubezhny** [comment]
Here is the result of executing 

```
mvn -U -B -ntp org.eclipse.dash:license-tool-plugin:license-check -Ddash.fail=true -X
```

locally on WWD project using the same branch as the one referenced in the GitHub License Check action:  [Dash License Tool maven plugin execution log](https://github.com/eclipse/dash-licenses/files/10197606/dlt.log.zip)

**Comment by vrubezhny** [comment]
Here are two more Orbit provided dependencies that make Dash License Tool Maven plugin to fail:
```
[INFO] p2/orbit/p2.eclipse.plugin/com.google.gson/2.10.1.v20230109-0753
[INFO] p2/orbit/p2.eclipse.plugin/org.apache.commons.compress/1.22.0.v20221207-1049
```
taken from https://github.com/eclipse/wildwebdeveloper/actions/runs/4426434464/jobs/7762716784 - a license verification job  for https://github.com/eclipse/wildwebdeveloper/pull/1128#top

**Comment by waynebeaton** [comment]
Both of these libraries have been scanned and determined to be under acceptable licenses. It appears that the scans were initiated with the proper GAVs (e.g., `com.google.code.gson:gson:2.10.1`). I believe that this is consistent with the way that Orbit builds: it pulls things from Maven Central using the standard GAV and repackages.

The challenge is that when the content is bundled, the mapping from from the actual Maven GAV to `p2.eclipse.plugin:com.google.gson:2.10.1.v20230109-0753` (or the ClearlyDefined equivalent) isn't obvious (note that the word `.code` is in the GAV, but is not present in the p2 id. We try to resolve this in a couple of ways, but none of those ways are magical enough to sort out what to do with the mapping.

I'll update the data to handle these two cases.

But... when this happens, please submit the content for review and we'll sort it out.

**Comment by waynebeaton** [comment]
So... while updating the data, I recalled another issue. Everything that I said previously about gson holds true. The commons-compress bundle is actually a manifestation of a different problem.

Sometimes the group id is expressed as `p2.eclipse.plugin` and sometimes it's expressed as `p2.eclipse-plugin`. Generally, the tool takes care of both, but we missed a corner case and the backend data expressed the id in a form that the tool couldn't map to the form you're using (`p2.eclipse.plugin`).

Anyway... it's fixed now. Both of those IDs return correct responses now.

Reopen if I've missed something.

**Comment by vrubezhny** [comment]
@waynebeaton Thanks. I'll try to get the dependencies from Maven and request for IP Team review for those I can't get from  there.
