### ISSUE TITLE
Getting `Can't write to target/dash/npm-deps-summary` error when using `-summary` argument

### ISSUE THREAD

**Issue by vrubezhny** [eclipse/dash-licenses#196]
When running dash-license tool snapshot project downloaded by maven and using `-summary` argument I get `Can't write to target/dash/npm-deps-summary` error

```
$ cd  <project>   # a project folder with package-lock.json file
$ mvn dependency:get -Dartifact=org.eclipse.dash:org.eclipse.dash.licenses:0.0.1-SNAPSHOT
...
$ java -jar $(ls ~/.m2/repository/org/eclipse/dash/org.eclipse.dash.licenses/0.0.1-SNAPSHOT/org.eclipse.dash.licenses-*.jar | head -n 1) ./package-lock.json -excludeSources local -summary target/dash/npm-deps-summary
Can't write to target/dash/npm-deps-summary
```

The error appears independently of existence of `<project>/target/dash/npm-deps-summary` folder.

**Comment by waynebeaton** [comment]
The code that prints that error is responding to a `FileNotFoundException` thrown by the `FileOutputStream` constructor.

Comments on the constructor state:

> If the file exists but is a **directory rather than a regular file**, does not exist but cannot be created, or cannot be opened for any other reason then a FileNotFoundException is thrown.

AFAICT, `target/dash` must exist and `target/dash/npm-deps-summary` must be a folder and not a directory.

I did make some unrelated changes last night, but I don't see how any of them would have affected this behaviour.

**Comment by vrubezhny** [comment]
> `target/dash/npm-deps-summary` must be a folder and not a directory.

Do you mean "file, not a directory"?

PS: I tested, and yes. "target/dash" is to be an existing directory, and "target/dash/npm-deps-summary" - a file is to be created /overwritten. I believe we can close the issue then. Sorry for the noise.

**Comment by waynebeaton** [comment]
> Do you mean "file, not a directory"?

Yes. Oops.

> I tested, and yes. "target/dash" is to be an existing directory, and "target/dash/npm-deps-summary" - a file is to be created /overwritten. 

Is there something misleading in the documentation that we need to fix?
