### ISSUE TITLE
npm dependencies have "Unknown_resolved_source()" as second field of identifier string instead of "npmjs"

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse/dash-licenses#197]
I think this is a relatively new issue, or at least I have not seen it before. When I ran `dash-licenses` on 3PPs a bunch came-out like this:

`npm/Unknown_resolved_source()/-/set-blocking/2.0.0`

Issues were automatically opened on Gitlab with corresponding title/content: I am manually editing them. e.g.:
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/5899

**Comment by marcdumais-work** [comment]
`dash-licenses` used above was downloaded like so : 
`"curl -L 'https://repo.eclipse.org/service/local/artifact/maven/redirect?r=dash-licenses&g=org.eclipse.dash&a=org.eclipse.dash.licenses&v=LATEST' -o dash-licenses.jar"`

**Comment by waynebeaton** [comment]
Weird. I'll have a look.

What content are you feeding to the tool?

**Comment by marcdumais-work** [comment]
These repos/version tags seem to trigger the issue:

https://github.com/microsoft/vscode-js-profile-visualizer , tag: v1.0.0
https://github.com/microsoft/vscode-js-debug , tag: v1.65.0

I ran the tool like so to reproduce the issue: 

```java -jar $DASH_LICENSES_JAR package-lock.json -timeout 120 -batch 20 -summary ./summary.txt```

**Comment by waynebeaton** [comment]
It appears that the source is set that way when anything that's resolved from a source that is not either local (file:) or from registry.npmjs.org is specified. I missed that when I accepted a related contribution. I'll sort it out.

**Comment by waynebeaton** [comment]
I can't repeat locally it in debugger.

Regardless, I've push a fix that decides that "npmjs" is a reasonable default should this ever come up again.

In the meantime, I'll poke at it a bit more and see if I can sort out what's happening.

**Comment by marcdumais-work** [comment]
How long before I can pick-up the updated .jar?

**Comment by waynebeaton** [comment]
It should be there now.

**Comment by marcdumais-work** [comment]
yep - work well now. Thanks!

**Comment by waynebeaton** [comment]
Okay. There it is...

````
    "node_modules/fsevents/node_modules/abbrev": {
      "version": "1.1.1",
      "integrity": "sha512-nne9/IiQ/hzIhY6pdDnbBtz7DjPTKrY00P/zvPSm5pOFkl6xuGrGnXn/VtTNNfNtAfZ9/1RtehkszU9qcTii0Q==",
      "dev": true,
      "inBundle": true,
      "optional": true
    },
````

The implementation, as of commit a625882735dc7ec46c1b51155280f8084ddde0b3 expected a "resolved" entry with a pointer to the download URL.

I don't understand `npm` well enough to be sure, but my best guess is that this is a nested node module that is contained within the parent and so it was not itself resolved. If that is indeed the case, then I guess that we should grab the "resolved" URL from the parent (recursively) to discover where the package comes from... 

Do you have any insight that would be helpful here, @mickaelistria ?

**Comment by mickaelistria** [comment]
Sorry, I don't have anything certain to help here, but your interpretation sounds good enough to me and the `inBundle` flag tends to comfort it.
