### ISSUE TITLE
"License information could not automatically verified" for Jakarta content

### ISSUE THREAD

**Issue by jonahgraham** [eclipse/dash-licenses#22]
I have run the license tool on CDT (full [maven.deps](https://github.com/eclipse/dash-licenses/files/5148206/maven.log)). I had a few false negatives (I believe).

This issue is for Jakarta entries that I believe are fine as they are from Eclipse:

- p2/orbit/p2.eclipse-plugin/org.glassfish.hk2.api/2.6.1.v20200513-1859 ()
- p2/orbit/p2.eclipse-plugin/org.glassfish.jersey.inject.jersey-hk2/2.30.1.v20200512-1802 ()
- p2/orbit/p2.eclipse-plugin/org.glassfish.hk2.osgi-resource-locator/1.0.3.v20200509-0149 ()
- p2/orbit/p2.eclipse-plugin/org.glassfish.jersey.apache.connector/2.30.1.v20200513-1859 ()
- p2/orbit/p2.eclipse-plugin/jakarta.xml.bind/2.3.3.v20200525-2159 ()
- p2/orbit/p2.eclipse-plugin/org.glassfish.hk2.locator/2.6.1.v20200513-1859 ()
- p2/orbit/p2.eclipse-plugin/org.glassfish.hk2.utils/2.6.1.v20200513-1859 ()

**Comment by waynebeaton** [comment]
Thanks for this. The `jakarta.xml` one is pretty easy, I'll add a rule to catch that. The `glassfish` ones are a little more challenging as some versions of Glassfish predate Eclipse GlassFish and the version numbers are all over the place. I'll see what I can come up with.

**Comment by waynebeaton** [comment]
Somewhere along the way, it appears that I sorted this out.
