### ISSUE TITLE
Add a parameter for the repository on Automatic IP Team Review Requests

### ISSUE THREAD

**Issue by AngelikaWittek** [eclipse/dash-licenses#224]
When the dash tool creates IPLab issues, it's not easy to find out which Eclipse project repository it came from. E.g. Eclipse Tractus-X has 36 repositories in its GitHub organization.
If you invoke the tool with the -review option, it would be helpful to have an option for the repository (e.g. the URL), which is also shown in the IPLab issue.

**Comment by HannesWell** [comment]
This is probably similar to https://github.com/eclipse/dash-licenses/issues/184 (but probably not a duplication).

**Comment by waynebeaton** [comment]
I've extended the tool to include a `-repo` option from the command line and a `dash.repo` property from Maven. When specified, the provided value is passed to IP Lab as the "Repository".

As an experiment... when not explicitly specified, the tool tries to figure it out by get trying to identify the Git repository that contains the working directory; when successful, it scans the remotes to try and find one that represents an Eclipse Project repository.

I'm going to experiment with a bit more and push it later tonight or tomorrow.

**Comment by HannesWell** [comment]
> I've extended the tool to include a `-repo` option from the command line and a `dash.repo` property from Maven. When specified, the provided value is passed to IP Lab as the "Repository".

That's nice. Could you additionally/alternatively also add a property to add arbitrary 'context' data like requested in #184, which would allow to add a link to the exact PR from which a request was created through the license workflow.
This would simplify for you or the IP team to get in touch with the initiators of the request.

**Comment by waynebeaton** [comment]
I can do that, but I'm leaning towards _additionally_ and so will take care of it in a separate commit.
