### ISSUE TITLE
Dash License Tool as a GitHub Action?

### ISSUE THREAD

**Issue by FaGru3n** [eclipse/dash-licenses#227]
Hi all,  👋🏼 

do you plan to create a GitHub Action to run DASH-Tool within an Action-Workflow-File?

So May you only have some inputs like language setting and the Token?

Would be very nice to run in automatically 😉 

Thank you in advance.

**Comment by waynebeaton** [comment]
I have no expertise in this area. 

My understanding is that [Reusable Github workflow for automatic license check and IP Team Review Requests](https://github.com/eclipse/dash-licenses#reusable-github-workflow-for-automatic-license-check-and-ip-team-review-requests) provides what you're looking for.

**Comment by FaGru3n** [comment]
Hi @waynebeaton,

thanks for helping. 😉

I will check if this suits our repositories but as a good start point, we can try this out.
