### ISSUE TITLE
"License information could not automatically verified" for stuff in Orbit

### ISSUE THREAD

**Issue by jonahgraham** [eclipse/dash-licenses#23]
I have run the license tool on CDT (full [maven.deps](https://github.com/eclipse/dash-licenses/files/5148206/maven.log)). I had a few false negatives (I believe).

This issue is for stuff in Orbit that I believe are fine - based on them being in https://download.eclipse.org/tools/orbit/downloads/drops/S20200826182026/

- p2/orbit/p2.eclipse-plugin/javax.annotation/1.3.5.v20200504-1837 ()
- p2/orbit/p2.eclipse-plugin/javax.ws.rs/2.1.6.v20200505-2127 ()

**Comment by waynebeaton** [comment]
It's probably a good bet that if something is in Orbit then it's probably fine. This is especially true for older stuff that predates the switch to our "license certification only" IP Policy. More recently, the Orbit project has started to only file CQs when they're needed, so there's more of a risk that something in Orbit might actually not be okay. My understanding is that the Orbit team is periodically running the license tool to validate.

In any case, I'll have a look at these specific dependencies and see what we need to do.

**Comment by waynebeaton** [comment]
Side note... clearly the regular expression in the README isn't right. I've seen this line a few times recently:

    tycho-compiler-plugin:1.7.0:compile

I'll see what I can do about that while I'm at it.

**Comment by jonahgraham** [comment]
> I'll see what I can do about that while I'm at it.

FWIW I tried to find something better, in the end there can be so much random output from mvn I went with the having mvn write the deps files itself. This is the command CDT's script uses:

```
${MVN:-mvn} -B -V package dependency:list -DappendOutput=true -DoutputFile=$PWD/deps-raw.log  >mvn-dependency-list.log 2>&1
```

with the deps-raw.log being a much cleaner output and used for further processing. This is in the README already, but not with an explicit example.

BTW I do this to deps-raw.log:

```
cat deps-raw.log | grep -v "The following files have been resolved" | grep -v "   none" | grep -Poh '[^ ]*' | sort -u > deps.log
```

**Comment by waynebeaton** [comment]
My affinity for trying to get everything onto one line has me biased against adding a step to generate the dependency list as a separate file. I think that I just need to get over that. I'll update the README to make that recommendation.

If you're not depending on a poorly crafted regexp, where is `tycho-compiler-plugin:1.7.0:compile` coming from?

**Comment by jonahgraham** [comment]
> If you're not depending on a poorly crafted regexp, where is `tycho-compiler-plugin:1.7.0:compile` coming from?

I was getting it when I filed #24 - but I have since closed it by doing what I mentioned here. When I closed it I didn't realize I had uncovered a general problem. HTH

**Comment by waynebeaton** [comment]
It just seems wrong to not use pipes... /shudder.

**Comment by waynebeaton** [comment]
The cited ids should pass now. Reopen if I've made a horrible, horrible mistake.
