### ISSUE TITLE
[enhancement] use a specific non-zero exit code to mean there was an "Internal Error"

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse/dash-licenses#236]
As a `dash-license` integrator, I wish there was a distinct non-zero exit code, to indicate that that there was an internal error, preventing the tool from running or from running to completion. It would make it possible to easily distinguish that case from the case where the tool was able to complete its work, but that some 3PPs were found to require more attention.

## `dash-licenses` exit code

_Currently:_
- `0`: great - the tool worked and no 3PP was found to require further attention
- `1`: it might be that one 3PP requires further attention or it might be that the tool was unable to run or to run to completion, for various reasons
- `[2, 127]`: two or more 3PPs require further attention

_Proposed:_
- `0`: great - the tool worked and no 3PP was found to require further attention
- `[1, 126]`: one or more 3PPs require further attention 
- `127`: internal error - the tool was unable to run or to run to completion. 

## What brought this up?

A committer reported a strange thing, in a recent `3PP License Check` [workflow log](https://github.com/eclipse-theia/theia/actions/runs/4882980758/jobs/8713726470?pr=12484#step:5:577) \[1\] : `dash-licenses` had thrown a run-time exception and exited early, but the workflow was still marked as a success.

From the log, everything was going-along fine but suddenly `clearlydefined` returned a `502` at one of `dash-licenses`' requests, which resulted in it exiting with exit code `1`, after about 1/3 of the 3PPs had been evaluated by the service. Not realizing `dash-licenses` had exited early, our script looked for flagged 3PPs in the summary file,  and concluded that zero 3PPs required more License attention, and so the workflow was considered a success \[2\].

With the proposed changes above, the same `502` error from `clearlydefined` would cause `dash-licenses` to exit with code `127`, which we can use in our integration, to fail the wrapper script and workflow (the workflow gets one retry before failing, and can be re-triggered). 

\[1\]: https://github.com/eclipse-theia/theia/actions/runs/4882980758/jobs/8713726470?pr=12484#step:5:577
```
[main] INFO Querying ClearlyDefined for license data for 50 items.
[main] ERROR Error response from ClearlyDefined 502
Error: Exception in thread "main" java.lang.RuntimeException: Received an error response from ClearlyDefined.
	at org.eclipse.dash.licenses.clearlydefined.ClearlyDefinedSupport.doQueryClearlyDefined(ClearlyDefinedSupport.java:174)
	at org.eclipse.dash.licenses.clearlydefined.ClearlyDefinedSupport.queryClearlyDefined(ClearlyDefinedSupport.java:123)
	at org.eclipse.dash.licenses.clearlydefined.ClearlyDefinedSupport.queryLicenseData(ClearlyDefinedSupport.java:102)
	at org.eclipse.dash.licenses.LicenseChecker.lambda$getLicenseData$3(LicenseChecker.java:52)
	at org.eclipse.dash.licenses.util.Batchifier.batchify(Batchifier.java:77)
	at org.eclipse.dash.licenses.LicenseChecker.getLicenseData(LicenseChecker.java:57)
	at org.eclipse.dash.licenses.cli.Main.lambda$main$5(Main.java:118)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.eclipse.dash.licenses.cli.Main.main(Main.java:100)
```

 
\[2\]: ![image](https://user-images.githubusercontent.com/25749063/236512380-e9d34ed4-98db-4d3f-989a-366088967d81.png)

**Comment by waynebeaton** [comment]
I'm seeing the 502 a lot more recently... I'll plug that hole. To the best of my knowledge the best way to deal with 502 is to just try again.

That besides, the current behaviour should be to return the number of libraries discovered that require further scrutiny (that is, the number that are not considered "approved").

Your suggestion seems reasonable, I'll see what I can do.

**Comment by marcdumais-work** [comment]
@waynebeaton I made this prototype to test against. You reuse reuse in part or in whole, as per this repo's license. Let me know if you'd like me to post as a PR. 
https://github.com/marcdumais-work/dash-licenses/commit/b48ffdbc17c0fbe2b84059f4b4de0ac3ae4dc435

**Comment by waynebeaton** [comment]
I've initiated a progress review. Following the success of that, I'll push out a release version based on the current state of the project. I'll start off the next version with this; so... send that pull request, please.
