### ISSUE TITLE
"License information could not automatically verified" for Tycho (compile)

### ISSUE THREAD

**Issue by jonahgraham** [eclipse/dash-licenses#24]
I have run the license tool on CDT (full [maven.deps](https://github.com/eclipse/dash-licenses/files/5148206/maven.log)). I had a few false negatives (I believe).

This issue is for Tycho compile time dependency:

- `#` tycho-compiler-plugin:1.7.0:compile (null)

**Comment by waynebeaton** [comment]
The server component identifies many artifacts as coming from Eclipse projects and categorizes them accordingly. Making this complete is always going to be a game of whack-a-mole with a risk that using wildcards to identify artifacts will incorrectly align similarly named third party content (I'm not sure whether or not this applies here). So, general sorts of "this includes an Eclipse project short name" filters can't work in the general case.

The GAV is incomplete...What's the groupid? (I'll try to whack this mole).

In the meantime, the workaround is to remove identifiers from the list that you don't want the tool to scan from your input. e.g., pipe input through `grep -v "^tycho"`. This tool is intended to assist with the process; I doubt that we'll ever be able to make it work 100% without committer interpretation of the results (works with dependencies are a particular challenge, see #13).

**Comment by jonahgraham** [comment]
> The server component identifies many artifacts as coming from Eclipse projects and categorizes them accordingly. Making this complete is always going to be a game of whack-a-mole with a risk that using wildcards to identify artifacts will incorrectly align similarly named third party content (I'm not sure whether or not this applies here). So, general sorts of "this includes an Eclipse project short name" filters can't work in the general case.

Fair enough.

> 
> The GAV is incomplete...What's the groupid? (I'll try to whack this mole).

`org.eclipse.tycho` - interesting the group id was missing from the maven.deps that was created, so I'll look to see why the grep doesn't extract it properly. It may be that once I get the grep right this problem goes away.


> 
> In the meantime, the workaround is to remove identifiers from the list that you don't want the tool to scan from your input. e.g., pipe input through `grep -v "^tycho"`. This tool is intended to assist with the process; I doubt that we'll ever be able to make it work 100% without committer interpretation of the results (works with dependencies are a particular challenge, see #13).

That is OK. This set of bugs were (what I believe) is low hanging fruit that is likely to hit numerous projects. Indeed most of them are actually dependencies of other Eclipse projects that CDT depends on.

**Comment by jonahgraham** [comment]
The missing group id was the key - the grep was picking out something nor from the `The following files have been resolved:` section of the output, but rather from this snippet of the full maven output:

```
[INFO] --- tycho-compiler-plugin:1.7.0:compile (default-compile) @ org.eclipse.cdt.lsp.cquery ---
[INFO] Nothing to compile - all classes are up to date
```

**Comment by jonahgraham** [comment]
I am closing for now as this issue is invalid. I will reopen if I come up with a simple/generic fix that can go in the readme.

**Comment by jonahgraham** [comment]
FWIW - the reason that this is a problem for CDT, but not for some other projects, is that `mvn dependency:list` on its own does not work for CDT because of complex dependencies within CDT, so instead I need to do `mvn package dependency:list` which means the compile phase runs, leading to the above snippet in my log that the grep misinteprets.

Therefore what is in the readme is the best in the general case and CDT will just be "special"
