### ISSUE TITLE
Uses maven dependencies in wrong scope

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse/dash-licenses#242]
Use the plugin with maven 3.9.2. Will have this warning at the end:
```
[WARNING]  * org.eclipse.dash:license-tool-plugin:1.0.2
...
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin should declare these Maven artifacts in `provided` scope: [org.apache.maven:maven-plugin-api:3.9.0, org.apache.maven:maven-artifact:3.9.0, org.apache.maven:maven-model:3.9.0]
```
See last bullet point of https://maven.apache.org/docs/3.9.2/release-notes.html#notable-new-features for the reason.

**Comment by waynebeaton** [comment]
This feels like it should be an easy fix, but when I change the scope, the build breaks. I clearly do not know Maven well enough. Help Wanted.
