### ISSUE TITLE
xmlgraphics 2.3.0 with valid CQ is shown as missing

### ISSUE THREAD

**Issue by akurtakov** [eclipse/dash-licenses#27]
Running license tool on tycho codebase shows p2/orbit/p2.eclipse-plugin/org.apache.xmlgraphics/2.3.0.v20190515-0436 ()
 as not auto verified but there is https://dev.eclipse.org/ipzilla/show_bug.cgi?id=19789 for it.

**Comment by waynebeaton** [comment]
I've actually been wrestling with this one for a few days (after looking at Tycho).

The fundamental problem is that the tool sees anything GAV with a groupid of "p2.eclipse-plugin" as coming from Orbit. But this particular version is not in Orbit. I had to tweak the backend to make this work. 

We may have to (longer term) introduce wildcard support in the "source" element. But, again, I think that this is a matter for the backend.

Anyway, it's fixed.
