### ISSUE TITLE
Problem parsing `yarn.lock` modified by `npm install`? 

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse/dash-licenses#281]
For a new project with a few devDependencies, I used the generated `yarn.lock` with `dash-licenses`. For some reason it seems that it does not like the file's format. e.g.:

```
X Invalid: "mocha@^10.2.0":, unknown
X Invalid: "ms@2.1.2":, unknown
X Invalid: "ms@2.1.3":, unknown
X Invalid: "nanoid@3.3.3":, unknown
X Invalid: "once@^1.3.0":, unknown
X Invalid: "p-limit@^3.0.2":, unknown
X Invalid: "p-locate@^5.0.0":, unknown
```

Just for fun, I tried using `npm install` instead of `yarn`, and the generated `package-lock.json` works perfectly with `dash-licenses`.

Comparing the new project's`yarn.lock` to one from another project's that works, I noticed dependencies entries fields are not in the same order:

_update: also, the new file seems adds double-quotes around field names and some values, that are not there in the old one_

does not parse:
```
"locate-path@^6.0.0":
  "integrity" "sha512-iPZK6eYjbxRu3uB4/WZ3EsEIMJFMqAoopl3R+zuq0UjcAm/MO6KCweDgPfP3elTztoKP3KtnVHxTn2NHBSDVUw=="
  "resolved" "https://registry.npmjs.org/locate-path/-/locate-path-6.0.0.tgz"
  "version" "6.0.0"
  dependencies:
    "p-locate" "^5.0.0"
```

parses: 
```
locate-path@^6.0.0:
  version "6.0.0"
  resolved "https://registry.yarnpkg.com/locate-path/-/locate-path-6.0.0.tgz#55321eb309febbc59c4801d931a72452a681d286"
  integrity sha512-iPZK6eYjbxRu3uB4/WZ3EsEIMJFMqAoopl3R+zuq0UjcAm/MO6KCweDgPfP3elTztoKP3KtnVHxTn2NHBSDVUw==
  dependencies:
    p-locate "^5.0.0"
```

I attach the `yarn.lock` causing issues: 
[yarn.lock.gz](https://github.com/eclipse/dash-licenses/files/13320027/yarn.lock.gz)

**Comment by marcdumais-work** [comment]
BTW, both `yarn.lock` files claim to be the same format version:

```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1
```

**Comment by marcdumais-work** [comment]
Update: I think my issue was that I ran a `npm install [..]` command, which is the one that modified the `yarn.lock`, turning it into the format that `dash-licenses` does not parse well. That's a bit unexpected and probably would not happen too often generally (yarn projects would tend to use `yarn add [...]`. 

I leave it up-to you, whether to consider making `dash-licenses` able to parse `npm`-modified `yarn-lock` files, would be a worthy enhancement. Else you may close this issue.

**Comment by waynebeaton** [comment]
Thanks for the investigative work. It is indeed the quotes around the key that cause the problem.

Unfortunately, I was not able to find any documentation on the format and so had to base the parser on observation alone. At least that was the case at the time.

The fix is easy enough. I'm just assembling a few more tests before I push it.

**Comment by waynebeaton** [comment]
I've pushed a fix to the master branch. Can you test it?

I'm way overdue to release an update. I'll try to get that done in the next week or so.
