### ISSUE TITLE
Remapping of package name is not detected in package-lock.json

### ISSUE THREAD

**Issue by spoenemann** [eclipse/dash-licenses#285]
See this IPLab issue which was created by Dash License Tool with the `-review` option:
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/11643

The Tool didn't detect that the actual package name is `strip-ansi`:
https://github.com/eclipse-langium/langium/blob/99bfb8577306d393d692e1e36e3b994ced81e87b/package-lock.json#L6706-L6707

This is due to a remapping of the package name in the dependencies of another package:
https://github.com/eclipse-langium/langium/blob/99bfb8577306d393d692e1e36e3b994ced81e87b/package-lock.json#L781

**Comment by waynebeaton** [comment]
Based on a cursory look, it appears that this is due to changes introduced with the version 3 format of the package lock schema. I believe that this is the same problem as in #284 .

**Comment by waynebeaton** [comment]
My initial assessment was partially correct, except that it's more that I missed a case when parsing version 3. It's a different problem from #284. The fix is relatively simple. I'll push it shortly.

**Comment by waynebeaton** [comment]
The Version 1.1.0 that I pushed to repo.eclipse.org last week should deal with this.
