### ISSUE TITLE
mavenLicenseCheck GH workflow is triggered (and immediately skipped) on every issue comment

### ISSUE THREAD

**Issue by rgrunber** [eclipse/dash-licenses#293]
We followed the instructions at https://github.com/eclipse/dash-licenses#reusable-github-workflow-for-automatic-license-check-and-ip-team-review-requests to set up the experimental license checking workflow in JDT-LS (https://github.com/eclipse-jdtls/eclipse.jdt.ls/blob/master/.github/workflows/licensecheck.yml) .

If you look at https://github.com/eclipse-jdtls/eclipse.jdt.ls/actions/workflows/licensecheck.yml (or even https://github.com/eclipse-m2e/m2e-core/actions/workflows/licensecheck.yml), you'll notice that every comment in an issue triggers the check (due to `issue_comment` trigger). It only uses a few seconds to determine the job should be skipped, so it would be hard to abuse, but it could still be a bit annoying to see that any user comment results in the workflow being triggered. 

According to https://github.com/eclipse/dash-licenses/blob/51f45991567a170692daba2759a454c9185c8d0f/.github/workflows/mavenLicenseCheck.yml#L49-L50 , the workflow will not proceed if `issue_comment` is the trigger, ~~so why not use [`pr_commented`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment-on-issues-only-or-pull-requests-only) in the instructions?~~

**Update** Ugh, I think I see the problem. The recommendation is exactly the workaround I linked. Looks like there's no way to determine prior to triggering whether the comment is from an issue or PR.

**Comment by HannesWell** [comment]
> , the workflow will not proceed if `issue_comment` is the trigger, ~so why not use [`pr_commented`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment-on-issues-only-or-pull-requests-only) in the instructions?~
> 
> **Update** Ugh, I think I see the problem. The recommendation is exactly the workaround I linked. Looks like there's no way to determine prior to triggering whether the comment is from an issue or PR.

Yes that's all totally right. I would have loved to do it differently, for the same reason, why you opened this issue, but unfortunately, as you already found out, that's the way to do it.
But I also have to admit that in the end it didn't bother me much, since the workflow runs are usually grouped any ways per workflow, so it is pretty easy to ignore these short runs.
And since public repos have unlimited workflow runtime, it is not really a problem.
