### ISSUE TITLE
Take some "originating Pull/Merge request" as input and store PR<->IP review link

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/dash-licenses#351]
One issue with current IP reviews is building the link between the PR(s) that require them and the IP reviews.
Most repos I work with do use the dash-license tool, and there are custom GitHub actions to create a GitHub comment for the created reviews. Although this doesn't always work well (because some repos have oddities that are not captured by the generic GitHub actions).
The link from a review to a PR has to be added manually, it requires first to find the review URL, then navigate there and then add the link. Note that only people registered as Eclipse.org users can perform those actions.
Then, it's up to committers to navigate the IP reviews occasionally for a given PR and when they're all good, they can finally merge the code.

We can probably do better/simpler here: the linkage could be provided automatically, and some GitHubp update/notification be implemented when an IP review is done.

Concretely, I suggest adding a `-originatingRequest <PR URL>` flag to dash-license tool.
When calling dash-license-tool with this flag, the dash-license tool would automatically:
1. Add as metadata or comment a link from the newly created or already found IP review to the pull-request
2. Add/Update a comment on the Pull-Request to list the related pending review at the time it's called.

Once those links are in, we can even have some bot that listens to IP review state and update the GitHub comment to mark the reviews as completed (update an existing comment), or send a comment when a review is rejected or when all known IP reviews pending for PR are fixed.

**Comment by mickaelistria** [comment]
(FYI, this is an idea I initially wrote down in the Eclipse committer satisfaction survey; but I think it can be actionable earlier by repeating it here)

**Comment by HannesWell** [comment]
Looks like a duplicate of https://github.com/eclipse/dash-licenses/issues/184 ?

**Comment by mickaelistria** [comment]
It is indeed. Let's close here as duplicate.
