### ISSUE TITLE
An NPE happens when using a package-lock.json as input

### ISSUE THREAD

**Issue by vrubezhny** [eclipse/dash-licenses#41]
An NPE happens when using a package-lock.json as input:
```
$ java -jar  org.eclipse.dash.licenses.jar package-lock.json
Nov 12, 2020 3:26:17 PM org.eclipse.dash.licenses.foundation.EclipseFoundationSupport queryLicenseData
INFO: Querying Eclipse Foundation for license data for 253 items.
Nov 12, 2020 3:26:19 PM org.eclipse.dash.licenses.foundation.EclipseFoundationSupport queryLicenseData
INFO: Found 89 items.
Nov 12, 2020 3:26:19 PM org.eclipse.dash.licenses.clearlydefined.ClearlyDefinedSupport queryLicenseData
INFO: Querying ClearlyDefined for license data for 164 items.
Exception in thread "main" java.lang.NullPointerException
	at org.eclipse.dash.licenses.LicenseChecker.lambda$getLicenseData$2(LicenseChecker.java:55)
	at org.eclipse.dash.licenses.clearlydefined.ClearlyDefinedSupport.lambda$queryLicenseData$1(ClearlyDefinedSupport.java:114)
	at java.base/java.util.Map.forEach(Map.java:661)
	at org.eclipse.dash.licenses.clearlydefined.ClearlyDefinedSupport.queryLicenseData(ClearlyDefinedSupport.java:111)
	at org.eclipse.dash.licenses.LicenseChecker.lambda$getLicenseData$3(LicenseChecker.java:54)
	at org.eclipse.dash.licenses.util.Batchifier.batchify(Batchifier.java:77)
	at org.eclipse.dash.licenses.LicenseChecker.getLicenseData(LicenseChecker.java:58)
	at org.eclipse.dash.licenses.cli.Main.lambda$main$2(Main.java:100)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.eclipse.dash.licenses.cli.Main.main(Main.java:87)
```

**Comment by waynebeaton** [comment]
I'll add some guard code to protect against the NPE. 

Having said that, it looks like ClearlyDefined is returning something unexpected that we'll need to handle (rather than discard). Can you give me the list of dependencies that you're feeding to the tool so that I can see what ClearlyDefined is returning?

**Comment by vrubezhny** [comment]
This zip contains a 'package-lock.json' that was used to produce the exception:
 
[package-lock.zip](https://github.com/eclipse/dash-licenses/files/5532362/package-lock.zip)

**Comment by waynebeaton** [comment]
Thanks.

The version information on five dependency entries is not in semantic version form. 

e.g., 

<pre>   "node-debug2": {
      "version": "file:target/node-debug2-1.42.2.tgz",
      "integrity": "sha512-oMAnv+jqPCdoKf1KUpLmx/wD14bALvfYDwCKa+usko1TImuskFPpvt7S1vH2e/Hg6GdUU48d0IustcRk7fNSqg==",
      "requires": {
        "minimatch": "^3.0.4",
        "vscode-chrome-debug-core": "^6.8.7",
        "vscode-debugadapter": "^1.37.1",
        "vscode-nls": "^4.0.0"
      }
    },</pre>

AFAIK, the [specification](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#version) states that the version must be expressed in semantic versioning. So this JSON file is--at least according to the specification--invalid.

Without additional information, I'll assume that this is a hack of some sort that's designed to use the version of a package that's included (i.e., that particular library is shipped along with the product, not pulled from the NPM repository). This is just a guess.

Frankly, I'm not sure what we can do with this information other than to make so that we at least fail gracefully. Other recommendations are welcome.

**Comment by waynebeaton** [comment]
I've just tested a fix that will flag these entries as invalid. So at least we'll now fail gracefully.

<pre>License information could not be automatically verified for the following content:

Invalid: -/debugger-for-chrome@file:target/debugger-for-chrome-4.12.8.tgz
Invalid: -/node-debug2@file:target/node-debug2-1.42.2.tgz
Invalid: -/vscode-css-languageserver@file:target/vscode-css-languageserver-1.0.0.tgz
Invalid: -/vscode-html-languageserver@file:target/vscode-html-languageserver-1.0.0.tgz
Invalid: -/vscode-json-languageserver@file:target/vscode-json-languageserver-1.2.3.tgz
npm/npmjs/-/less/3.12.2
npm/npmjs/-/native-request/1.0.8
npm/npmjs/-/tslib/1.14.1
npm/npmjs/-/vscode-debugprotocol/1.42.0
npm/npmjs/@types/json5/0.0.29
npm/npmjs/@types/source-map/0.1.29

This content is either not correctly mapped by the system, or requires review.</pre>

After looking closer, it appears that the version numbers of the components are embedded in the URI. AFAICT, debugger-for-chrome@4.12.8 isn't in the NPMJS repository, so perhaps this is a pre-release version?

**Comment by vrubezhny** [comment]
I don't think these are a subject to be contributed into NPMJS repository in the closest future.  These components are installed from the according pre-downloaded archives by maven build by executing a command like 
```
npm install --no-bin-link --ignore-scripts <path-to-tgz-module-archive>...
```
So, imho, actually these "invalid" versions are assigned to these modules by `npm` itself

**Comment by waynebeaton** [comment]
I'm going to push the fix so that we get back to a state where we're not breaking.

**Comment by waynebeaton** [comment]
Pushed ab7dcb976e43ab27d2b0dcba5932aafa61310c30

**Comment by waynebeaton** [comment]
> So, imho, actually these "invalid" versions are assigned to these modules by `npm` itself

I can't find any reference to this form. Can you have a look to see if this sort of use is documented?

We can make, I think, a pretty good guess that we can just pull the version number out of the file name, but I'd like to do a little due diligence first.

**Comment by vrubezhny** [comment]
> I can't find any reference to this form. Can you have a look to see if this sort of use is documented?

It's documented at https://docs.npmjs.com/cli/v6/commands/npm-install in `npm install <tarball file>:` section:
```
 Install a package that is sitting on the filesystem. Note: if you just want to link a dev directory into your npm root, you can do this more easily by using npm link.

Tarball requirements:

    The filename must use .tar, .tar.gz, or .tgz as the extension.

    The package contents should reside in a subfolder inside the tarball (usually it is called package/). npm strips one directory layer when installing the package (an equivalent of tar x --strip-components=1 is run).

    The package must contain a package.json file with name and version properties.

    Example:

npm install ./package.tgz
```

**Comment by vrubezhny** [comment]
Not reproducible anymore.
Thanks
