### ISSUE TITLE
Not all problems are visible with a multi-module POM

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/dash-licenses#42]
In https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22896#c5, @waynebeaton mentioned that some Kotlin dependencies were identified as problematic but I am unable to see them in my tool output. Could you please help me run it with the right arguments? Using aba7d20607f9ca5ab65833367b03b0cb4f1e9255 and ggrep (GNU grep) 3.6 packaged by Homebrew.

`mvn dependency:list | ggrep -Poh "\S+:(system|provided|compile)" | sort | uniq 
 | java -jar ../misc/dash-licenses/target/org.eclipse.dash.licenses-0.0.1-SNAPSHOT.jar -`

> Dec 08, 2020 4:58:27 PM org.eclipse.dash.licenses.foundation.EclipseFoundationSupport queryLicenseData
> INFO: Querying Eclipse Foundation for license data for 203 items.
> Dec 08, 2020 4:58:30 PM org.eclipse.dash.licenses.foundation.EclipseFoundationSupport queryLicenseData
> INFO: Found 148 items.
> Dec 08, 2020 4:58:30 PM org.eclipse.dash.licenses.clearlydefined.ClearlyDefinedSupport queryLicenseData
> INFO: Querying ClearlyDefined for license data for 55 items.
> Dec 08, 2020 4:58:33 PM org.eclipse.dash.licenses.clearlydefined.ClearlyDefinedSupport queryLicenseData
> INFO: Found 55 items.
> License information could not be automatically verified for the following content:
> 
> maven/mavencentral/com.google.code.findbugs/jsr305/3.0.2
> maven/mavencentral/javax.servlet.jsp.jstl/javax.servlet.jsp.jstl-api/1.2.2
> maven/mavencentral/org.apache.jena/jena-querybuilder/3.14.0
> maven/mavencentral/org.glassfish.jersey.bundles.repackaged/jersey-guava/2.25.1
> 
> This content is either not correctly mapped by the system, or requires review.

Repo is https://github.com/eclipse/lyo @v4.0.0.RC (HEAD)

P.S. Thank you for finally buiding this tool 😍

**Comment by waynebeaton** [comment]
The tool doesn't know anything about modules or Maven (beyond the ability to parse Maven GAVs). It only knows that you feed it. If you think that there's a problem with modules, then we'll need to sort out a better means of querying the information from Maven before passing it to the tool.

In this case, it looks like some ClearlyDefined magic happened. 

When I ran the tool earlier, it identified four Kotlin dependencies, but I'm not seeing them anymore. It appears that they're now being passed by ClearlyDefined. 

When you query ClearlyDefined for data that it doesn't have, it queues the entry up for research. So the harvester probably went out and found the content in the meantime.

Note that if you use the "-summary DEPENDENCIES" option, the tool will generate a report of all of the content, along with license information, and the source of the information (my thinking is that this file will become part of the IP Log at some point).

    $ grep kotlin DEPENDENCIES 
    maven/mavencentral/org.jetbrains.kotlin/kotlin-stdlib-common/1.4.20, Apache-2.0, approved, clearlydefined
    maven/mavencentral/org.jetbrains.kotlin/kotlin-stdlib/1.4.20, Apache-2.0, approved, clearlydefined
    maven/mavencentral/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.4.20, Apache-2.0, approved, clearlydefined
    maven/mavencentral/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.4.20, Apache-2.0, approved, clearlydefined
    $ _

So no CQ is required for these Kotlin dependencies.

This is probably a good example of why project teams should run the license tool periodically. This is good information to provide in the documentation.

> P.S. Thank you for finally buiding this tool

A lot of things came together to make building the tool possible. I am also happy that we are finally able to automate this and am looking forward to further automation. See #34
