### ISSUE TITLE
Publish maven plugin 

### ISSUE THREAD

**Issue by akurtakov** [eclipse/dash-licenses#45]
In order to be able to use the new maven-plugin it has to be published to maven repository. It's too early to think of maven central so probably https://repo.eclipse.org/ is best.

**Comment by msohn** [comment]
Pushed https://github.com/eclipse/dash-licenses/pull/48 for review.
Someone with access to the build configuration needs to configure Maven to run the deploy phase.
And maybe some configuration is needed to grant acccess to Nexus to the Jiro instance used by dash.

**Comment by waynebeaton** [comment]
Any volunteers?

Unfortunately, I've never done any of the above and am starting from zero knowledge.

**Comment by akurtakov** [comment]
Is there JIPP for dash?

**Comment by waynebeaton** [comment]
There is. I guess that I have some homework to do.

**Comment by waynebeaton** [comment]
I've created a [build](https://ci.eclipse.org/dash/job/dash-license-tool/). I'll try to sort out how to push the results to repo.eclipse.org later this afternoon.

**Comment by msohn** [comment]
I guess Fred knows how to configure that

**Comment by waynebeaton** [comment]
I've [requested](https://bugs.eclipse.org/bugs/show_bug.cgi?id=570377) some space on repo.eclipse.org.

**Comment by waynebeaton** [comment]
> I guess Fred knows how to configure that

That's a pretty good guess. :-)

**Comment by msohn** [comment]
here is the documentation how to deploy build artefacts to repo.eclipse.org
https://wiki.eclipse.org/Jenkins#How_can_artifacts_be_deployed_to_Nexus_OSS_.28repo.eclipse.org.29.3F

**Comment by waynebeaton** [comment]
Deployed. Look [here](https://repo.eclipse.org/index.html#view-repositories;dash-licenses-snapshots~browsestorage~/org/eclipse/dash/license-tool-plugin/0.0.1-SNAPSHOT/license-tool-plugin-0.0.1-20210124.234121-1.jar).

The job is currently configured to run manually.

**Comment by msohn** [comment]
I tried to run this on the jgit project but the plugin can't be run since jgit is still compiled using java 8 since there are a lot of consumers which can't cope with java 11 yet.

Could you compile the maven plugin using java 8 ?

**Comment by waynebeaton** [comment]
> Could you compile the maven plugin using java 8 ?

Sorry for the delay. I tried and I failed.

It fails to compile because we're using some classes introduced in Java 11 (e.g., java.net.http.HttpResponse).

My sense is that we still have a significant number of projects still building on Java 8 and that we should address this.   The original code ran using Apache HttpClient. I'll investigate reverting to that.

**Comment by msohn** [comment]
thanks

in the interim until this is available we can run
mvn org.eclipse.dash:license-tool-plugin:license-check -Ddash.summary=DEPENDENCIES
using Java 11 after running the actual jgit build using java 8

**Comment by waynebeaton** [comment]
So... dumb question, but I can't seem to quite sort out the magic myself.

How do I pull the plugin from repo.eclipse.org and invoke the plugin from the CLI? I'm trying to set the -Dmaven.repo.remote to point to repo.eclipse.org, but can't get it work.

> $ mvn org.eclipse.dash:license-tool-plugin:license-check -Dmaven.repo.remote=http://repo.eclipse.org/content/repositories/snapshots/ -Dmaven.repo.local=/tmp/mvn 
> ...
> [ERROR] Plugin org.eclipse.dash:license-tool-plugin:license-check or one of its dependencies could not be resolved

(I'm pointing the local repo into /tmp to avoid it picking up the version of the plugin that I've installed in my local repo).

**Comment by akurtakov** [comment]
You have to define it as pluginRepository and unfortunately I'm not aware of a way to do it via cli so pom.xml has to define it.

**Comment by akurtakov** [comment]
Done and I use it in lsp4e and tycho.

**Comment by waynebeaton** [comment]
Reopening. I regard "publishing" as making available on Maven Central.

I think that we need to enable committers to just `mvn org.eclipse.dash:license-tool-plugin:license-check` and have magic happen.

**Comment by waynebeaton** [comment]
I've changed my mind. This is a speciality tool (at least for now). Expanding access to a broader audience isn't a goal. Unless somebody can convince me otherwise, I no longer regard publishing to Maven Central as appropriate.
