### ISSUE TITLE
felix.gogo.command not recognized as OK - but felix.gogo.runtime is

### ISSUE THREAD

**Issue by jonahgraham** [eclipse/dash-licenses#49]
I guess the metadata about felix.gogo.command is not correct somehow - but not sure. Both f.g.command and f.g.runtime are in latest [orbit release](https://download.eclipse.org/tools/orbit/downloads/drops/R20201130205003/) with CQ [22658](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22658) and CQ [22659](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22659) respectively.

If this isn't a bug in dash-licenses, I would be happy to fix it where it is - but I don't know where/how to do that.

felix.gogo.command:

```
 $ echo p2.eclipse-plugin:org.apache.felix.gogo.command:jar:1.1.0.v20201023-1558:system | java -jar dash-licenses/core/target/org.eclipse.dash.licenses-*-SNAPSHOT.jar -
Jan 11, 2021 8:33:45 PM org.eclipse.dash.licenses.foundation.EclipseFoundationSupport queryLicenseData
INFO: Querying Eclipse Foundation for license data for 1 items.
Jan 11, 2021 8:33:45 PM org.eclipse.dash.licenses.foundation.EclipseFoundationSupport queryLicenseData
INFO: Found 0 items.
License information could not be automatically verified for the following content:

p2/orbit/p2.eclipse-plugin/org.apache.felix.gogo.command/1.1.0.v20201023-1558

This content is either not correctly mapped by the system, or requires review.
```

felix.gogo.runtime
```
$ echo p2.eclipse-plugin:org.apache.felix.gogo.runtime:jar:1.1.2.v20201023-1558:system | java -jar dash-licenses/core/target/org.eclipse.dash.licenses-*-SNAPSHOT.jar -
Jan 11, 2021 8:33:48 PM org.eclipse.dash.licenses.foundation.EclipseFoundationSupport queryLicenseData
INFO: Querying Eclipse Foundation for license data for 1 items.
Jan 11, 2021 8:33:48 PM org.eclipse.dash.licenses.foundation.EclipseFoundationSupport queryLicenseData
INFO: Found 1 items.
Vetted license information was found for all content. No further investigation is required.

```

**Comment by waynebeaton** [comment]
It's all about the data in the back end. One is in the back end mapping between content and CQs and one is not. Or rather, that was the condition. Both are in the mapping now.

One way to fix this is to use the ClearlyDefined ID as the summary when you create the CQ. Otherwise, I just have to map it.
