### ISSUE TITLE
Running on Mac

### ISSUE THREAD

**Issue by phkrief** [eclipse/dash-licenses#5]
Hi Wayne,

Knowing some of us are using a MacOS machines, will it make sense to mention in the readme file for Mac users must install the GNU grep on their machine first
> brew install grep
and then replace each instance of grep in the doc by ggrep?

Actually, the current grep on Mac doesn't support the -P option.

Kind regards

**Comment by waynebeaton** [comment]
I'm dumbfounded that grep isn't installed by default on a UNIX-based system.

Do you really mean "ggrep"?

Regardless, can make a pull request to the README that provides some MacOS examples?

FWIW, I'm using grep in the examples because I wanted to keep the tool simple and focused. Perhaps we can extend the tool to do the parsing instead of expecting it to be pre-parsed with command-line tools.

**Comment by phkrief** [comment]
Yes, I really meant ggrep with 2 'g'. Please check out: https://binx.io/blog/2018/11/19/learning-grep/

> Regardless, can make a pull request to the README that provides some MacOS examples?
Do you ask me to submit these pull request? I'm fine with that. I want just to be sure that I understand your point.

> FWIW, I'm using grep in the examples because I wanted to keep the tool simple and focused. Perhaps we can extend the tool to do the parsing instead of expecting it to be pre-parsed with command-line tools.
Yes, it would be another option, knowing yours is pretty elegant ;-)

**Comment by phkrief** [comment]
> I'm dumbfounded that grep isn't installed by default on a UNIX-based system.

It is installed but it doesn't cover this -P parameter (which seems to be experimental, btw see https://www.gnu.org/software/grep/manual/grep.html#Command_002dline-Options)

**Comment by waynebeaton** [comment]
> Do you ask me to submit this pull request?

Yes. I don't have the means to test anything on a Mac, so anything that I add would be guesses.

**Comment by phkrief** [comment]
Sure ! I will do it.
Thx
