### ISSUE TITLE
Return non-0 in case a dependency is invalid

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/dash-licenses#6]
Looking at the code, it seems like the application will always return success when listing the dependencies+IP status. In order to more easily and reliably integrate with other tools and workflows if the application would return an error/non-0 code in case a dependency isn't conform to Eclipse IP Policy. This tool could then be used to fail a build and automate a -1 vote on code-review.

**Comment by waynebeaton** [comment]
FWIW, the output is currently just a quick and dirty hack. You have to interpret it (i.e., understand that "restricted" has some meaning), which makes it less useful than it can be. I'm thinking that we need the ability to get the tool to (configurable) output the CSV list of content and licenses, but also some form of "here's what you need to do" output.

But yes, having a non-0 return code in cases where the discovered license coverage is anything less than 100% makes good sense.

**Comment by waynebeaton** [comment]
I implemented this a while ago. The return value is the number of "problematic" hits.
