### ISSUE TITLE
Add timeout CLI param

### ISSUE THREAD

**Issue by ffendt** [eclipse/dash-licenses#63]
Currently the request timeout for HTTP commands is hard coded to 60 seconds in [ISettings.java:78](https://github.com/eclipse/dash-licenses/blob/635dc2e98c03d249a74864f8294bb68a8f163e26/core/src/main/java/org/eclipse/dash/licenses/ISettings.java#L78).

This isn't enough for medium sized `package-lock.json` files.

As a user I would like to have another CLI-param (e.g. `-request-timeout <timeout>`) to set the timeout in seconds without having to change the code.

**Comment by waynebeaton** [comment]
Implemented in 61496a8484617ac2402e243317b3f8720c00abac.

I went with `-timeout` since the extra dash messed up the command line parser.

**Comment by ffendt** [comment]
Thank you very much, that was fast.
