### ISSUE TITLE
org.eclipse.rcp_root being rejected by dash

### ISSUE THREAD

**Issue by jonahgraham** [eclipse/dash-licenses#68]
Hello EMO,

The Dash license check on LSP4E is rejecting some content from Eclipse itself:

```
License information could not be automatically verified for the following content:

maven/mavencentral/p2.p2-installable-unit/org.eclipse.rcp_root/4.18.0.v20201202-1800

```

Is this something that can be tuned on the dash licenses side? Please let me know what additional info you need. 

Thanks
Jonah

**Comment by waynebeaton** [comment]
I ran into this last week in a different context. 

I've fixed it on the server, so it should just work now.

**Comment by jonahgraham** [comment]
FWIW I just ran and hit the same error - https://ci.eclipse.org/lsp4e/job/gerrit_code_review_test/job/master/58/console

**Comment by jonahgraham** [comment]
Please consider reopening - I am seeing the same thing for rcp_root 4.19:

```
21:13:34  maven/mavencentral/p2.p2-installable-unit/org.eclipse.platform_root/4.19.0.v20210303-1800
```

from https://ci.eclipse.org/cdt/view/Main%20(diagnostic%20builds)/job/cdt-master-run-dash-licenses/15/

**Comment by waynebeaton** [comment]
It took an embarrassingly long time to notice that the ID is actually different.

Both `org.eclipse.rcp_root` and `org.eclipse.platform_root` now map to the Eclipse Platform project. 

If you can think of any other variations, please reopen.

I had thought about generalizing this further to `org.eclipse.*_root`, but doing so may have unanticipated consequences.

**Comment by waynebeaton** [comment]
I'll add `org.eclipse.platform.*` and `org.eclipse.rcp.*` as _Eclipse Platform_ patterns. I believe that shouldn't result in any invalid hits.
