### ISSUE TITLE
Provide option to fail Maven build on non-approved dependencies

### ISSUE THREAD

**Issue by dhendriks** [eclipse/dash-licenses#70]
The license check Maven plugin is nice. It would be even better if it also had an option to fail the build if any dependencies are non-approved. Then we could enable that for releases, to ensure we don't release with non-approved dependencies.

**Comment by waynebeaton** [comment]
Great idea. I especially like the idea of making it an _option_ to fail the build (as opposed to making it fail the build by default).

**Comment by waynebeaton** [comment]
I've added a `dash.fail` parameter. The default setting is `false`. When this parameter is set to true and the plugin finds at least one problematic library, the Maven plugin throws a `MojoFailureException` which causes the build to fail.
