### ISSUE TITLE
Sort summary file generated by Maven plugin 

### ISSUE THREAD

**Issue by dhendriks** [eclipse/dash-licenses#72]
It would be great if the `summary` file generated by the Maven plugin would be sorted. That would be much more readable.

**Comment by msohn** [comment]
+1, we check in the dependency list before the release, when the file is sorted it's easy to check the diff against the previous release. Currently we sort it manually before checkin.

**Comment by waynebeaton** [comment]
Resolved in e4c0affdf90df046d6daf8e5d46f1f4d38d0d72e.

**Comment by 0388324575** [comment]
> It would be great if the `summary` file generated by the Maven plugin would be sorted. That would be much more readable.
