### ISSUE TITLE
Non-deterministic license check result

### ISSUE THREAD

**Issue by dhendriks** [eclipse/dash-licenses#95]
Eclipse ESCET has an automatic license check build on Jenkins. I got a failure, so I adapted the output. Then I ran it again, and it wants the old output again. I keep having to change it back and forth. The output is not deterministic.

Builds 92/95:
```
p2/orbit/p2.eclipse-plugin/org.apache.xerces/2.12.1.v20210115-0812, Apache-2.0 AND W3C-19980720, approved, CQ16951
```

Builds 93/94/96:
```
p2/orbit/p2.eclipse-plugin/org.apache.xerces/2.12.1.v20210115-0812, , approved, CQ16951
```

What causes this? Any way it can be made consistent/deterministic?

(The last change to CQ16951 itself seems to have been about 1.5 months ago.)

**Comment by waynebeaton** [comment]
That was a tough one to sort out. It appears that there is a subtle difference in the PCRE implementation on the new server that caused the regular expression that we use to validate the SPDX expression to produce a different result. 

The backend grabs the license list directly from spdx.org and manipulates it into a regular expression that includes a massive "or" list of SPDX license ids. We had previously just rendered the list in the order it was received with an understanding that the regular expression implementation didn't care about the order in the "or" list. My assumption is that the greediness of the regular expression algorithm effectively hid certain licenses. The solution was to change the sort order.

Note that both earlier and later versions of the PCRE implementation did not exhibit this limitation. Regardless, the changed implementation appears to be getting it right on all the versions that I've tested it on.
