### ISSUE TITLE
Create a `npm` cli package to wrap `dash-licenses` for node projects?

### ISSUE THREAD

**Issue by paul-marechal** [eclipse/dash-licenses#96]
Might depend on https://github.com/eclipse/dash-licenses/issues/94

In the [Eclipse Theia repository](https://github.com/eclipse-theia/theia) we ended up writing a JS script to wrap `dash-licenses` and provide some features like ignoring specific reports from the `dash-licenses` output.

The idea would be to publish a package on `npm` to distribute and use `dash-licenses` in node applications.

Features might include:

- Download latest `dash-licenses` upon install.
- Run `dash-licenses`.
- Ignore reports of specific dependencies via some configuration.

The main benefit would be to make it easy to use: a simple `npm i --save-dev dash-licenses` and then `npx dash-licenses`.

We could contribute an initial implementation for such a package if you find the idea useful.

**Comment by waynebeaton** [comment]
It certainly sounds interesting.

**Comment by sbernard31** [comment]
(For curious people, Theia dash-licences integration code is available [here](https://github.com/eclipse-theia/theia/blob/v1.19.0/scripts/check_3pp_licenses.js))

**Comment by paul-marechal** [comment]
@sbernard31 thanks for the link! Once we find time for it we shall extract it into it's own independent package. We just haven't found the time to set that up properly yet.

**Comment by marcdumais-work** [comment]
@waynebeaton FYI, I'm working on this - we have several repositories under "eclipse-cdt-cloud" that would benefit, and probably others as well.

**Comment by marcdumais-work** [comment]
A new repository was created for the dash-licenses wrapper and I opened a PR there: https://github.com/eclipse-dash/nodejs-wrapper/pull/1

**Comment by marcdumais-work** [comment]
The PR above was merged. Now we just need to figure-out the details of publishing it to `npm`.

**Comment by marcdumais-work** [comment]
Update: We have manually published v0.0.1 to npm (still working on the automated publishing infrastructure), and have updated several repos in project `ecd.cdt-cloud` to use the new package, as part of GitHub CI, so we can catch 3PPs with suspicious or unclear licenses, as early as possible. So I think it's ready for some friendly testing/usage, by other JS/TS EF projects/repos.

Package:
https://www.npmjs.com/package/@eclipse-dash/nodejs-wrapper
Example of an integration into one of our repos:
https://github.com/eclipse-cdt-cloud/vscode-trace-extension/pull/190/files

**Comment by marcdumais-work** [comment]
@waynebeaton I think we can probably close this issue here?  

Any questions related to the wrapper can be directed here: 
https://github.com/eclipse-dash/nodejs-wrapper/issues
